theme: jekyll-theme-minimal
title: Flynn homepage
description: Welcome to your Site!
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
